name: Helm Google Cloud
description: "Use Helm with Google Cloud Kubernetes Engine"
author: "Hannes Lohmander"
inputs:
  gcloudAuth:
    required: true
    description: Base64 encoded JSON credentials for GCLOUD
  projectName:
    required: true
    description: The name of the Google Cloud project
  clusterName:
    required: true
    description: The Kubernetes cluster name
  clusterZone:
    required: true
    description: The Kubernetes cluster zone
  chartPath:
    required: false
    description: The path to the Helm chart
    default: chart
  releaseName:
    required: true
    description: The Helm release name to upgrade
  set:
    required: false
    description: Override values using --set
runs:
  using: "docker"
  image: "Dockerfile"
